# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", 
            artifact: "windows.x64.py38.tar.xz",
            os: windows-latest,
            python-version: 3.8,
            architecture: x64
          }


    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}

    - name: Run show_info.py
      run: |
        python show_info.py


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel

    - name: Build Windows Python
      run: |
        cd pkg
        python setup.py build --build-lib=lib bdist_wheel 

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: pkg/dist