# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        # python 3.7 (macOS and Ubuntu has no x86 version)
        #- { name: "macOS (py37_x64)", os: macos-latest, python-version: 3.7, architecture: x64, artifact_name: "macos-latest.py37_x64.whl.zip" }
        #- { name: "Ubuntu (py37_x64)", os: ubuntu-latest, python-version: 3.7, architecture: x64, artifact_name: "ubuntu-latest.py37_x64.whl.zip" }
        #- { name: "Windows MSVC (py37_x64)", os: windows-latest, python-version: 3.7, architecture: x64, artifact_name: "windows-latest.py37_x64.whl.zip" }
        #- { name: "Windows MSVC (py37_x86)", os: windows-latest, python-version: 3.7, architecture: x86, artifact_name: "windows-latest.py37_x86.whl.zip" }

        # python 3.8 (macOS and Ubuntu has no x86 version)
        #- { name: "macOS (py38_x64)", os: macos-latest, python-version: 3.8, architecture: x64, artifact_name: "macos-latest.py38_x64.whl.zip" }
        - { name: "Ubuntu (py38_x64)", os: ubuntu-latest, python-version: 3.8, architecture: x64, artifact_name: "ubuntu-latest.py38_x64.whl.zip" }
        #- { name: "Windows MSVC (py38_x64)", os: windows-latest, python-version: 3.8, architecture: x64, artifact_name: "windows-latest.py38_x64.whl.zip" }
        #- { name: "Windows MSVC (py38_x86)", os: windows-latest, python-version: 3.8, architecture: x86, artifact_name: "windows-latest.py38_x86.whl.zip" }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: ${{ matrix.config.architecture }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Run show_info.py
      run: |
        python show_info.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel flake8 pytest

    - name: Build package (setup.py)
      run: |
        cd pkg
        python setup.py build --build-lib=lib bdist_wheel 

    - name: Test with pytest
      run: |
        pytest -vv -r s

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.artifact_name }}
        path: pkg/dist/*.whl

