name: Python + CPP package

on:
  push:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!.gitattributes'
      - '!.gitmodules'
      - '!.gitignore'
      - '!external/**'
      - '!docs/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'
      - '!**.md'
      - '!.gitattributes'
      - '!.gitmodules'
      - '!.gitignore'
      - '!external/**'
      - '!docs/**'


jobs:
  build_test_ubuntu_py38_x64:
    # test build only on one config, if all ok, then run same steps on other configs
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true # fail-fast: true meant that if one test fail, then all running tests will be canceled
      matrix:
        config:
        - { name: "Ubuntu (py38_x64)", os: ubuntu-latest, python-version: 3.8, architecture: x64, artifact_name: "ubuntu-latest.py38_x64.whl.zip" }
        - { name: "macOS (py38_x64)", os: macos-latest, python-version: 3.8, architecture: x64, artifact_name: "macos-latest.py38_x64.whl.zip" }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}
        architecture: ${{ matrix.config.architecture }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel flake8 pytest

    - name: Build package (setup.py)
      run: |
        cd pkg
        python setup.py build --build-lib=lib bdist_wheel
        cd ..

    - name: Install package (dist/*.whl)
      run: |
        cd pkg
        python install_dist.py
        cd ..

    - name: Run show_info.py
      run: |
        python show_info.py

    - name: Test with builtin test function
      run: |
        python -c "import actions_python_cpp_compiler; actions_python_cpp_compiler.run_tests()"

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.artifact_name }}
        path: pkg/dist/*.whl

  release:
    needs: [build_test_ubuntu_py38_x64]
    name: "release"
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'false'
 
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
 
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist
 
    - name: Create Release
      id: upload-release-asset 
      uses: softprops/action-gh-release@v1
      with:
        files: |
            dist/**.whl
        body_path: ${{ github.workflow }}/readme.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
